env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'no-use-before-define': 'off'
  '@typescript-eslint/no-use-before-define': ['error']
  'react/jsx-filename-extension': [1, { 'extensions': ['.tsx'] }]
  'import/extensions':
    [
      'error',
      'ignorePackages',
      { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' },
    ]
settings:
  import/resolver:
    typescript: {}
